<a href="https://colab.research.google.com/github/2303a51541/AIML/blob/main/p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#lists in python(PART1)
import numpy as np
thislist = [1,3,5,7,9]
print(thislist)

[1, 3, 5, 7, 9]


In [14]:
import pandas as pd
thislist = [2,4,6,8,10]
print(thislist)

[2, 4, 6, 8, 10]


In [19]:
#arrays using numpy
import numpy as np
cars = ["PORSCHE", "RANGE ROVER", "BMW"]
arr = np.array(cars)
print(arr)

['PORSCHE' 'RANGE ROVER' 'BMW']


In [18]:
import pandas as pd
odd = [1,3,5,7,9]
arr = pd.Series(odd)
print(arr)


0    1
1    3
2    5
3    7
4    9
dtype: int64


In [ ]:
#types using numpy
import numpy as np
arr = np.array(["zobiya","spriha","bhavya"])
print(arr.dtype)

<U6


In [21]:
import pandas as pd
arr = pd.Series(["zobiya","spriha","bhavya"])
print(arr.dtype)

object


In [1]:
#mathematical operations using numpy
import numpy as np
a = np.array([7,8,9])
b = np.array([3,4,5])
np.multiply= a*b
print("multiplication= ",(np.multiply))
np.divide= a/b
print("divide= ",(np.divide))
np.poweroff= a%b
print("poewroff= ",(np.poweroff))

multiplication=  [21 32 45]
divide=  [2.33333333 2.         1.8       ]
poewroff=  [1 0 4]


In [24]:
import pandas as pd
a = pd.Series([7,8,9])
b = pd.Series([3,4,5])
pd.multiply= a*b
print("multiplication= ",(pd.multiply))
pd.divide= a/b
print("divide= ",(pd.divide))
pd.poweroff= a%b
print("poewroff= ",(pd.poweroff))

multiplication=  0    21
1    32
2    45
dtype: int64
divide=  0    2.333333
1    2.000000
2    1.800000
dtype: float64
poewroff=  0    1
1    0
2    4
dtype: int64


In [9]:
#combine text using numpy
import numpy as np
arr1 = np.array("Addition of two: ")
arr2 = np.array("array1 + array2")
result =np.char.add(arr1, arr2)

print(result)


Addition of two: array1 + array2


In [28]:
import pandas as pd
arr1 = pd.Series("Addition of two: ")
arr2 = pd.Series("array1 + array2")
result =arr1.str.cat(arr2)
print(result)

0    Addition of two: array1 + array2
dtype: object


In [13]:
#implementation of np.sin() , log() , log2() , np.exp())
#np.sin()
import numpy as np
a = np.array([7,8,9])
b = np.sin(a)
print(b)
#log()
c = np.log(a)
print(c)
#log2()
d = np.log2(a)
print(d)
#np.exp()
e = np.exp(a)
print(e)

[0.6569866  0.98935825 0.41211849]
[1.94591015 2.07944154 2.19722458]
[2.80735492 3.         3.169925  ]
[1096.63315843 2980.95798704 8103.08392758]
